from enum import Enum

class Roles(Enum):
    ADMIN = "ADMIN"
    PREP_RESIDENTIELS = "PREP_RESIDENTIEL"
    PREP_AFFAIRE = "PREP_AFFAIRE"
    CLIENT_RESIDENTIELS = "CLIENT_RESIDENTIELS"
    CLIENT_AFFAIRE = "CLIENT_AFFAIRE"