from enum import Enum

class Roles(Enum):
    SUPER_ADMIN = "SUPER_ADMIN"
    ADMIN = "ADMIN"
    PREP_RESIDENTIEL = "PREP_RESIDENTIEL"
    PREP_AFFAIRE = "PREP_AFFAIRE"
    CLIENT_RESIDENTIEL = "CLIENT_RESIDENTIEL"
    CLIENT_AFFAIRE = "CLIENT_AFFAIRE"
    TEMPORARY = "TEMPORARY"